<a href="https://colab.research.google.com/github/Rahmatul-Rovi/Machine-Learning-Practice/blob/main/NumPy_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Normal list vs NumPy array
normal_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])
print(normal_list)
print(np_array)

print(np_array * 2)
print(np_array + 10)
print(np_array ** 2)

# Important functions
marks = np.array([85, 90, 78, 92, 88, 76, 95])
print(f"Average: {np.mean(marks):.2f}")
print(f"Highest: {np.max(marks)}")
print(f"Lowest: {np.min(marks)}")
print(f"Total: {np.sum(marks)}")

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]
Average: 86.29
Highest: 95
Lowest: 76
Total: 604
